// <auto-generated />
using CommandQueryResponsibilitySegregation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommandQueryResponsibilitySegregation.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommandQueryResponsibilitySegregation.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (byte)20,
                            Name = "Zaminali",
                            Surname = "Rustamov"
                        },
                        new
                        {
                            Id = 2,
                            Age = (byte)21,
                            Name = "Nicat",
                            Surname = "Abdullayev"
                        },
                        new
                        {
                            Id = 3,
                            Age = (byte)19,
                            Name = "Ali",
                            Surname = "Ibrahimov"
                        },
                        new
                        {
                            Id = 4,
                            Age = (byte)21,
                            Name = "Namiq",
                            Surname = "Mikayilov"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
